# Projet Walmart sales

Bloc3 : PROJECTS Supervised Machine Learning

Walmart sales

360 min

https://app.jedha.co/course/projects-supervised-machine-learning-ft/walmart-sales-ft

## Company's Description 📇

Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores from the United States, headquartered in Bentonville, Arkansas. The company was founded by Sam Walton in 1962.

## Project 🚧

Walmart's marketing service has asked you to build a machine learning model able to estimate the weekly sales in their stores, with the best precision possible on the predictions made. Such a model would help them understand better how the sales are influenced by economic indicators, and might be used to plan future marketing campaigns.

## Goals 🎯

The project can be divided into three steps:

- Part 1 : make an EDA and all the necessary preprocessings to prepare data for machine learning
- Part 2 : train a **linear regression model** (baseline)
- Part 3 : avoid overfitting by training a **regularized regression model**

In [95]:
# import libraries for EDA
import pandas as pd
import numpy as np

# Visualization libraries
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


#from src.eda import *
# import libraries for modeling
# preprocessing selection
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
# model selection
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import cross_val_score, GridSearchCV
# model evaluation

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from fpcia import score_model,summary,how_null_is_it,explode_date,remove_duplicates

In [96]:

# For reproducibility
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

## Part 0 : import dataset and inception

We import the csv dataset into a pandas dataframe and have a first look to the datastructure.
Since we know that original data come from Kaggle before modifying by Jedha, we watch in Kaggle about the meaning of eaxh column. 
This is the historical data that covers sales from 2010-02-05 to 2012-11-01, in the file Walmart_Store_sales. Within this file you will find the following fields:


 |  column name   |   description   |  
 |  -------- | ------- |
 | Store | the store number | 
 | Date | the week of sales | 
 | Weekly_Sales  |  sales for the given store | 
 |  Holiday_Flag  | whether the week is a special holiday week <br /> 1 – Holiday week <br /> 0 – Non-holiday week | 
 | Temperature |  Temperature on the day of sale | 
 | Fuel_Price  |  Cost of fuel in the region | 
 | CPI |  Prevailing consumer price index  | 
 | Unemployment  |  Prevailing unemployment rate  | 
 

 L'indice des prix à la consommation ou IPC (en anglais, consumer price index ou CPI) mesure l'évolution du niveau moyen des prix des biens et services consommés par les ménages, pondérés par leur part dans la consommation moyenne des ménages. L'indice (105 par exemple) permet de mesurer l'inflation (ici +5 % de hausse des prix), ou la déflation en cas de baisse des prix, sur une période et donc l'évolution de la valeur de la monnaie (la valeur de la monnaie diminue lorsque les prix augmentent). Le taux (annuel) d'inflation désigne généralement, lorsque l'indice n'est pas précisé, le pourcentage d'augmentation de cet indice (IPC) particulier sur une année.

In [97]:
df= pd.read_csv("Data/Walmart_Store_sales.csv")
summary(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         150 non-null    float64
 1   Date          132 non-null    object
 2   Weekly_Sales  136 non-null    float64
 3   Holiday_Flag  138 non-null    float64
 4   Temperature   132 non-null    float64
 5   Fuel_Price    136 non-null    float64
 6   CPI           138 non-null    float64
 7   Unemployment  135 non-null    float64
dtypes: float64(7), object(1)
memory usage: 9.5+ KB

"________________________________________________\nData Start\n   Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \\\n0    6.0  18-02-2011    1572117.54           NaN        59.61       3.045   \n1   13.0  25-03-2011    1807545.43           0.0        42.38       3.435   \n2   17.0  27-07-2012           NaN           0.0          NaN         NaN   \n3   11.0         NaN    1244390.03           0.0        84.57         NaN   \n4    6.0  28-05-2010    1644470.66           0.0        78.89       2.759   \n5    4.0  28-05-2010    1857533.70           0.0          NaN       2.756   \n6   15.0  03-06-2011     695396.19           0.0        69.80       4.069   \n7   20.0  03-02-2012    2203523.20           0.0        39.93       3.617   \n8   14.0  10-12-2010    2600519.26           0.0        30.54       3.109   \n9    3.0         NaN     418925.47           0.0        60.12       3.555   \n\n          CPI  Unemployment  \n0  214.777523         6.858  \n1  128.616064         7.470  \n2  130.719581         5.936  \n3  214.556497         7.346  \n4  212.412888         7.092  \n5  126.160226         7.896  \n6  134.855161         7.658  \n7  213.023622         6.961  \n8         NaN           NaN  \n9  224.132020         6.833  \n________________________________________________\nData End\n     Store        Date  Weekly_Sales  Holiday_Flag  Temperature  Fuel_Price  \\\n140    3.0  07-01-2011           NaN           0.0        53.35       2.976   \n141    5.0  12-11-2010     301827.36           0.0        62.37         NaN   \n142    3.0  07-10-2011     403342.40           0.0        75.54       3.285   \n143    3.0  04-06-2010     396968.80           0.0        78.53       2.705   \n144    3.0  19-10-2012     424513.08           0.0        73.44       3.594   \n145   14.0  18-06-2010    2248645.59           0.0        72.62       2.780   \n146    7.0         NaN     716388.81           NaN        20.74       2.778   \n147   17.0  11-06-2010     845252.21           0.0        57.14       2.841   \n148    8.0  12-08-2011     856796.10           0.0        86.05       3.638   \n149   19.0  20-04-2012    1255087.26           0.0        55.20       4.170   \n\n            CPI  Unemployment  \n140  214.695510         7.551  \n141  212.560411         6.768  \n142         NaN         7.197  \n143  214.495838         7.343  \n144  226.968844         6.034  \n145  182.442420         8.899  \n146         NaN           NaN  \n147  126.111903           NaN  \n148  219.007525           NaN  \n149  137.923067         8.150  \n________________________________________________\nThe shape of the dataset is: (150, 8)\n________________________________________________\ncolumns of the dataset \nIndex(['Store', 'Date', 'Weekly_Sales', 'Holiday_Flag', 'Temperature',\n       'Fuel_Price', 'CPI', 'Unemployment'],\n      dtype='object')\n________________________________________________\ndata describe : \n             Store        Date  Weekly_Sales  Holiday_Flag  Temperature  \\\ncount   150.000000         132  1.360000e+02    138.000000   132.000000   \nunique         NaN          85           NaN           NaN          NaN   \ntop            NaN  19-10-2012           NaN           NaN          NaN   \nfreq           NaN           4           NaN           NaN          NaN   \nmean      9.866667         NaN  1.249536e+06      0.079710    61.398106   \nstd       6.231191         NaN  6.474630e+05      0.271831    18.378901   \nmin       1.000000         NaN  2.689290e+05      0.000000    18.790000   \n25%       4.000000         NaN  6.050757e+05      0.000000    45.587500   \n50%       9.000000         NaN  1.261424e+06      0.000000    62.985000   \n75%      15.750000         NaN  1.806386e+06      0.000000    76.345000   \nmax      20.000000         NaN  2.771397e+06      1.000000    91.650000   \n\n        Fuel_Price         CPI  Unemployment  \ncount   136.000000  138.000000    135.000000  \nunique         NaN         NaN           NaN  \ntop            NaN         NaN           NaN  \nfreq           NaN         NaN           NaN  \nmean      3.320853  179.898509      7.598430  \nstd       0.478149   40.274956      1.577173  \nmin       2.514000  126.111903      5.143000  \n25%       2.852250  131.970831      6.597500  \n50%       3.451000  197.908893      7.470000  \n75%       3.706250  214.934616      8.150000  \nmax       4.193000  226.968844     14.313000  \n________________________________________________\ndata info : \nNone\n________________________________________________\ntypes in dataset :\nStore           float64\nDate             object\nWeekly_Sales    float64\nHoliday_Flag    float64\nTemperature     float64\nFuel_Price      float64\nCPI             float64\nUnemployment    float64\ndtype: object\n________________________________________________\nOverall missing values in dataset : 103\nmissing values in dataset per column \n    Store            0\nDate            18\nWeekly_Sales    14\nHoliday_Flag    12\nTemperature     18\nFuel_Price      14\nCPI             12\nUnemployment    15\ndtype: int64\n________________________________________________________________________________________________\n"

In [98]:
display(df)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,6.0,18-02-2011,1572117.54,NaN,59.61,3.045,214.777523,6.858
1,13.0,25-03-2011,1807545.43,0.0,42.38,3.435,128.616064,7.470
2,17.0,27-07-2012,NaN,0.0,NaN,NaN,130.719581,5.936
3,11.0,NaN,1244390.03,0.0,84.57,NaN,214.556497,7.346
4,6.0,28-05-2010,1644470.66,0.0,78.89,2.759,212.412888,7.092
...,...,...,...,...,...,...,...,...
145,14.0,18-06-2010,2248645.59,0.0,72.62,2.780,182.442420,8.899
146,7.0,NaN,716388.81,NaN,20.74,2.778,NaN,NaN
147,17.0,11-06-2010,845252.21,0.0,57.14,2.841,126.111903,NaN
148,8.0,12-08-2011,856796.10,0.0,86.05,3.638,219.007525,NaN
149,19.0,20-04-2012,1255087.26,0.0,55.20,4.170,137.923067,8.150

We noticed also that the Store is an integer id to identify the store. We convert it into intger since the store sounds more like a classification than a regression value.

In [99]:
df=df.dropna()
df.reset_index(drop=True)
df.shape

(75, 8)

In [100]:
df = df.astype({"Store": int, "Holiday_Flag": int, "Weekly_Sales": float, "Temperature": float, "Fuel_Price": float, "CPI": float, "Unemployment": float},errors='ignore')
df.dtypes
df

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
1,13,25-03-2011,1807545.43,0,42.38,3.435,128.616064,7.470
4,6,28-05-2010,1644470.66,0,78.89,2.759,212.412888,7.092
6,15,03-06-2011,695396.19,0,69.80,4.069,134.855161,7.658
7,20,03-02-2012,2203523.20,0,39.93,3.617,213.023622,6.961
10,8,19-08-2011,895066.50,0,82.92,3.554,219.070197,6.425
...,...,...,...,...,...,...,...,...
139,7,25-05-2012,532739.77,0,50.60,3.804,197.588605,8.090
143,3,04-06-2010,396968.80,0,78.53,2.705,214.495838,7.343
144,3,19-10-2012,424513.08,0,73.44,3.594,226.968844,6.034
145,14,18-06-2010,2248645.59,0,72.62,2.780,182.442420,8.899
149,19,20-04-2012,1255087.26,0,55.20,4.170,137.923067,8.150

The date is an object time, we need to convert in real date figures (new column dt) from the string format _day_-_month_-_year_ (`"%d-%m-%Y"`)

In [101]:
#df['dt'] = pd.to_datetime(df["Date"], format = "%d-%m-%Y")
#df.dtypes

We split the date on year, month and week.

In [102]:
df=explode_date(df,'Date', format = "%d-%m-%Y")
display(df)
print()
display(df.dtypes)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
1,13,2011-03-25,1807545.43,0,42.38,3.435,128.616064,7.470,2011,3,12,25,0,0,0
4,6,2010-05-28,1644470.66,0,78.89,2.759,212.412888,7.092,2010,5,21,28,0,0,0
6,15,2011-06-03,695396.19,0,69.80,4.069,134.855161,7.658,2011,6,22,3,0,0,0
7,20,2012-02-03,2203523.20,0,39.93,3.617,213.023622,6.961,2012,2,5,3,0,0,0
10,8,2011-08-19,895066.50,0,82.92,3.554,219.070197,6.425,2011,8,33,19,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,7,2012-05-25,532739.77,0,50.60,3.804,197.588605,8.090,2012,5,21,25,0,0,0
143,3,2010-06-04,396968.80,0,78.53,2.705,214.495838,7.343,2010,6,22,4,0,0,0
144,3,2012-10-19,424513.08,0,73.44,3.594,226.968844,6.034,2012,10,42,19,0,0,0
145,14,2010-06-18,2248645.59,0,72.62,2.780,182.442420,8.899,2010,6,24,18,0,0,0
149,19,2012-04-20,1255087.26,0,55.20,4.170,137.923067,8.150,2012,4,16,20,0,0,0

Store                    int64
Date            datetime64[ns]
Weekly_Sales           float64
Holiday_Flag             int64
Temperature            float64
Fuel_Price             float64
CPI                    float64
Unemployment           float64
Year                     Int64
Month                    Int64
Week                     Int64
Day                      Int64
Hour                     Int64
Minute                   Int64
second                   Int64
dtype: object

## Part 1 : Exploration, Exploratory data analysis (EDA)

In [103]:
# Constant for the layout of the plots
WIDTH = 600
HEIGHT = 400
MARGIN = 30

In [104]:
# Compute total revenue cumulated by day
df_store = df.groupby('Store')['Week'].count().reset_index()
df_store.sort_values(by='Store',ascending= False)
fig = px.pie(df_store, names = "Store", values = "Week")
fig.show()

In [105]:
orders_store_by_weekly_sales=df.groupby(['Store'])[['Weekly_Sales']].mean()
orders_store_by_weekly_sales.sort_values(by='Weekly_Sales',ascending= False)
orders_year_by_weekly_sales=df.groupby(['Year'])[['Weekly_Sales']].mean()
orders_month_by_weekly_sales=df.groupby(['Month'])[['Weekly_Sales']].mean()
orders_week_by_weekly_sales=df.groupby(['Week'])[['Weekly_Sales']].mean()
orders_week_by_weekly_sales.sort_values(by='Weekly_Sales',ascending= False)

#px.bar(orders_year_by_weekly_sales, x= orders_year_by_weekly_sales.index, y='Weekly_Sales', 
#        title="Average Weekly Sales by Year", labels={"x":"Store","Weekly_Sales":"Average Weekly Sales per Year"}).show()
#px.bar(orders_store_by_weekly_sales, x= orders_store_by_weekly_sales.index, y='Weekly_Sales', title="Average Weekly Sales by Store", labels={"x":"Store","Weekly_Sales":"Average Weekly Sales per store"}).show()
#px.bar(orders_month_by_weekly_sales, x= orders_month_by_weekly_sales.index, y='Weekly_Sales', title="Average Weekly Sales by Month", labels={"x":"Month","Weekly_Sales":"Average Weekly Sales per month"}).show()
#px.bar(orders_week_by_weekly_sales, x= orders_week_by_weekly_sales.index, y='Weekly_Sales', title="Average Weekly Sales", labels={"x":"Month","Weekly_Sales":"Average Weekly Sales"}).show()

fig = make_subplots(rows = 4, cols = 1, subplot_titles = (["Wallmart average weekly sales per store",
                                        "Wallmart average weekly sales per year",
                                        "Wallmart average weekly sales per month",
                                        "Wallmart average weekly sales per week"] ))
fig.add_bar(

        x = orders_store_by_weekly_sales.index,
        y = orders_store_by_weekly_sales.Weekly_Sales,
        row = 1,
        col = 1

)    
fig.add_bar(
        x = orders_year_by_weekly_sales.index,
        y = orders_year_by_weekly_sales['Weekly_Sales'],
        row = 2,
        col = 1

)    
fig.add_bar(

        x = orders_month_by_weekly_sales.index,
        y = orders_month_by_weekly_sales['Weekly_Sales'],
        row = 3,
        col = 1
)    
fig.add_bar(
        x = orders_week_by_weekly_sales.index,
        y = orders_week_by_weekly_sales['Weekly_Sales'],
        row = 4,
        col = 1
)    
layout = go.Layout(
    title = go.layout.Title(text = "Weekly Sales", x = 1.0),
    showlegend = False,
    autosize=False,
    width=1000,
    height=2000,
    xaxis=go.layout.XAxis(linecolor="black", linewidth=1, mirror=True),
    yaxis=go.layout.YAxis(linecolor="black", linewidth=1, mirror=True),
    margin=go.layout.Margin(l=50, r=50, b=100, t=100, pad=4),
)

fig.update_layout(layout)
#px.bar(orders_store_by_weekly_sales, x= orders_store_by_weekly_sales.index, y='Weekly_Sales', title="Average Weekly Sales by Store", labels={"x":"Store","Weekly_Sales":"Average Weekly Sales"}).show()

In [106]:
orders_month_by_weekly_sales=df.groupby(['Month'])[['Weekly_Sales']].sum()
orders_month_by_weekly_sales.sort_values(by='Weekly_Sales',ascending= False)
fig = px.line(orders_month_by_weekly_sales, x=orders_month_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by Month", width=WIDTH, height=HEIGHT)
fig = px.scatter(orders_month_by_weekly_sales, x=orders_month_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by Month", width=WIDTH, height=HEIGHT)
#fig.update_traces(marker=dict(size=12, color='LightSkyBlue', line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig.update_layout(margin=dict(l=MARGIN, r=MARGIN, t=MARGIN, b=MARGIN))
px.density_heatmap(orders_month_by_weekly_sales, x=orders_month_by_weekly_sales.index, y='Weekly_Sales', nbinsx=20, nbinsy=10, width=WIDTH, height=HEIGHT)
px.box(df, x='Month', y='Weekly_Sales', width=WIDTH, height=HEIGHT)
fig = px.line(orders_month_by_weekly_sales, x=orders_month_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by Month", width=WIDTH, height=HEIGHT)
fig.show()

In [107]:
orders_month_by_weekly_sales

       Weekly_Sales
Month
1        1758050.79
2        9747718.72
3       11250266.88
4        5631856.38
5        7670030.46
6       10141497.56
7       11887829.82
8        5876256.19
9        4550383.33
10       4590653.94
11       6444107.92
12      10630713.52

In [108]:
orders_week_by_weekly_sales=df.groupby(['Week'])[['Weekly_Sales']].sum()
orders_week_by_weekly_sales.sort_values(by='Weekly_Sales',ascending= False)
fig = px.line(orders_week_by_weekly_sales, x=orders_week_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by week", width=WIDTH, height=HEIGHT)
fig = px.scatter(orders_week_by_weekly_sales, x=orders_week_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by week", width=WIDTH, height=HEIGHT)
#fig.update_traces(marker=dict(size=12, color='LightSkyBlue', line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))
fig.update_layout(margin=dict(l=MARGIN, r=MARGIN, t=MARGIN, b=MARGIN))
px.density_heatmap(orders_week_by_weekly_sales, x=orders_week_by_weekly_sales.index, y='Weekly_Sales', nbinsx=20, nbinsy=10, width=WIDTH, height=HEIGHT)
px.box(df, x='Week', y='Weekly_Sales', width=WIDTH, height=HEIGHT)
fig = px.line(orders_week_by_weekly_sales, x=orders_week_by_weekly_sales.index, y='Weekly_Sales', title="Total Weekly Sales by Week", width=WIDTH, height=HEIGHT)
fig.show()

In [109]:
orders_week_by_weekly_sales

      Weekly_Sales
Week
1       1758050.79
5       2665145.42
6       3200219.61
7       2020550.99
8       1861802.70
9       1990371.02
11      4273666.63
12      4501133.82
13      1046240.55
15       757738.76
16      3351786.25
17       961186.23
18      2426161.92
19      2631260.92
20       435397.19
21      2177210.43
22      3127796.38
24      2612722.44
25      4400978.74
26      3567333.39
27      2420253.12
28      1953544.76
29      2036231.39
30      1910467.16
31      1166117.85
32      2926255.06
33       895066.50
34       888816.78
36      1500995.58
37       836707.85
38      2212679.90
39       829207.27
41      3023575.44
42       737871.23
45      2228719.44
46      2458145.97
47      1757242.51
49      4763973.21
50      4067002.52
52      1799737.79

In [110]:
fig = px.line(orders_week_by_weekly_sales, x=orders_week_by_weekly_sales.index, y='Weekly_Sales' , title='Weekly Sales according to week', width=WIDTH, height=HEIGHT)
fig.update_layout(margin=dict(l=MARGIN, r=MARGIN, t=MARGIN, b=MARGIN))

In [111]:
fig = px.line(orders_month_by_weekly_sales, x=orders_month_by_weekly_sales.index, y='Weekly_Sales' , title='Weekly Sales according to month', width=WIDTH, height=HEIGHT)
fig.update_layout(margin=dict(l=MARGIN, r=MARGIN, t=MARGIN, b=MARGIN))

In [112]:
dfcpi=df[df['CPI'].notna()]
cpi_over_store = dfcpi.groupby('Store')['CPI'].mean()
display(cpi_over_store)

Store
1     215.252979
2     214.333910
3     220.325272
4     128.727135
5     217.419409
6     214.713791
7     195.476131
8     215.876613
9     215.437285
10    130.682713
11    215.061403
12    127.810020
13    128.864857
14    186.141628
15    136.219774
16    193.255923
17    127.968344
18    135.566845
19    134.483065
20    207.411465
Name: CPI, dtype: float64

In [113]:
px.density_heatmap(df, x='Store', y='Weekly_Sales', nbinsx=20, nbinsy=40, width=WIDTH, height=HEIGHT)

In [114]:
orders_month_by_weekly_sales=df.groupby(['Year','Month'])['Weekly_Sales'].sum()
display(orders_month_by_weekly_sales)

Year  Month
2010  2        3098381.06
      3        1427023.45
      4        1318883.90
      5        3138722.16
      6        4982827.11
      7        5816911.71
      8        2054934.63
      9        1739826.88
      10       1858825.37
      11       4193878.55
      12       7859316.35
2011  1        1758050.79
      3        3074110.37
      4        1639358.93
      5        2161575.73
      6        2703741.11
      7        4264918.32
      8        3821321.56
      9        2212679.90
      11       2250229.37
      12       2771397.17
2012  2        6649337.66
      3        6749133.06
      4        2673613.55
      5        2369732.57
      6        2454929.34
      7        1805999.79
      9         597876.55
      10       2731828.57
Name: Weekly_Sales, dtype: float64

In [115]:
orders_month_by_weekly_sales.index

MultiIndex([(2010,  2),
            (2010,  3),
            (2010,  4),
            (2010,  5),
            (2010,  6),
            (2010,  7),
            (2010,  8),
            (2010,  9),
            (2010, 10),
            (2010, 11),
            (2010, 12),
            (2011,  1),
            (2011,  3),
            (2011,  4),
            (2011,  5),
            (2011,  6),
            (2011,  7),
            (2011,  8),
            (2011,  9),
            (2011, 11),
            (2011, 12),
            (2012,  2),
            (2012,  3),
            (2012,  4),
            (2012,  5),
            (2012,  6),
            (2012,  7),
            (2012,  9),
            (2012, 10)],
           names=['Year', 'Month'])

In [116]:
year=2010
orders_month_by_weekly_sales.loc[year]

Month
2     3098381.06
3     1427023.45
4     1318883.90
5     3138722.16
6     4982827.11
7     5816911.71
8     2054934.63
9     1739826.88
10    1858825.37
11    4193878.55
12    7859316.35
Name: Weekly_Sales, dtype: float64

In [117]:
orders_month_by_weekly_sales=df.groupby(['Year','Month'])['Weekly_Sales'].sum()
dfm=orders_month_by_weekly_sales
years = [2010, 2011, 2012]

fig = go.Figure()

visible = True, False, False, False, False

for i, year in enumerate(years):
    if i == 0:
        fig.add_trace(
            go.Scatter(
                x=dfm[year].index,
                y=dfm,
                visible=True
            )
        )

    else:
        fig.add_trace(
            go.Scatter(
                x=dfm[year].index,
                y=dfm,
                visible=False
            )
        )
        


fig.update_layout(
    updatemenus=[go.layout.Updatemenu(
        active=0,
        buttons=[
            go.layout.updatemenu.Button(
                label="2010",
                method='update',
                args=[{'visible': [True,  False, False],
                        "xaxis": dict(range=[1, 12], title="Month", tick0=1,dtick=1)
                }]
            ),
            go.layout.updatemenu.Button(
                label="2011",
                method='update',
                args=[{'visible': [False,  True,  False],
                        "xaxis": dict(range=[1, 12], title="Month", tick0=1,dtick=1)
                }]
            ),
            go.layout.updatemenu.Button(
                label="2012",
                method='update',
                args=[{'visible': [False, False,  True],
                        "xaxis": dict(range=[1, 12], title="Month", tick0=1,dtick=1)
                }]
            ),
            
        ]
    )]
)

fig.update_layout(title=dict(text="Monthly Sales observations in a chosen year", x=0.5))

fig.show()

In [118]:
orders_week_by_weekly_sales=df.groupby(['Year','Week'])['Weekly_Sales'].sum()
dfw=orders_week_by_weekly_sales
years = [2010, 2011, 2012]

fig = go.Figure()

visible = True, False, False, False, False

for i, year in enumerate(years):
    if i == 0:
        fig.add_trace(
            go.Scatter(
                x=dfw[year].index,
                y=dfw,
                visible=True
            )
        )

    else:
        fig.add_trace(
            go.Scatter(
                x=dfw[year].index,
                y=dfw,
                visible=False
            )
        )
        


fig.update_layout(
    updatemenus=[go.layout.Updatemenu(
        active=0,
        buttons=[
            go.layout.updatemenu.Button(
                label="2010",
                method='update',
                args=[{'visible': [True,  False, False],
                        "xaxis": dict(range=[1, 52], title="Week", tick0=1,dtick=4)
                }]
            ),
            go.layout.updatemenu.Button(
                label="2011",
                method='update',
                args=[{'visible': [False,  True,  False],
                        "xaxis": dict(range=[1, 52], title="Week", tick0=1,dtick=4)
                }]
            ),
            go.layout.updatemenu.Button(
                label="2012",
                method='update',
                args=[{'visible': [False, False,  True],
                       "xaxis": dict(range=[1, 52], title="Week", tick0=1,dtick=4)
                }]
            ),
            
        ]
    )]
)

fig.update_layout(title=dict(text="Weekly Sales observations in a chosen year", x=0.5))

fig.show()

In [119]:
df_c=df.drop(columns=['Date'])
# Correlation
df_corr = df_c.corr().round(1)  
# Mask to matrix
mask = np.zeros_like(df_corr, dtype=bool)
mask[np.triu_indices_from(mask)] = True
# Viz
df_corr_viz = df_corr.mask(mask).dropna(how='all').dropna( how='all')
fig = px.imshow(df_corr_viz, text_auto=True)
fig.show()

In [120]:
df_corr

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
Store,1.0,0.2,-0.0,-0.2,0.2,-0.6,0.2,-0.0,-0.0,-0.0,-0.0,NaN,NaN,NaN
Weekly_Sales,0.2,1.0,-0.0,-0.1,-0.1,-0.4,-0.0,-0.1,0.0,0.0,-0.1,NaN,NaN,NaN
Holiday_Flag,-0.0,-0.0,1.0,-0.2,-0.2,0.2,0.2,-0.1,0.0,0.0,-0.0,NaN,NaN,NaN
Temperature,-0.2,-0.1,-0.2,1.0,-0.0,0.1,0.0,-0.1,0.2,0.2,0.1,NaN,NaN,NaN
Fuel_Price,0.2,-0.1,-0.2,-0.0,1.0,-0.2,0.0,0.8,-0.2,-0.2,0.0,NaN,NaN,NaN
CPI,-0.6,-0.4,0.2,0.1,-0.2,1.0,-0.3,0.0,-0.1,-0.1,0.2,NaN,NaN,NaN
Unemployment,0.2,-0.0,0.2,0.0,0.0,-0.3,1.0,-0.2,0.0,0.0,-0.2,NaN,NaN,NaN
Year,-0.0,-0.1,-0.1,-0.1,0.8,0.0,-0.2,1.0,-0.3,-0.3,-0.0,NaN,NaN,NaN
Month,-0.0,0.0,0.0,0.2,-0.2,-0.1,0.0,-0.3,1.0,1.0,0.0,NaN,NaN,NaN
Week,-0.0,0.0,0.0,0.2,-0.2,-0.1,0.0,-0.3,1.0,1.0,0.1,NaN,NaN,NaN
Day,-0.0,-0.1,-0.0,0.1,0.0,0.2,-0.2,-0.0,0.0,0.1,1.0,NaN,NaN,NaN
Hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Minute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
second,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
px.imshow(df_c.corr())

# 0.0 - 0.3 = No correlation
# 0.3 - 0.5 = Weak correlation
# 0.5 - 0.7 = Moderate correlation
# 0.7 - 1.0 = Strong correlation

In [122]:
Sales_per_week=df.groupby(['Year','Week'])[['Weekly_Sales','CPI',"Temperature"]].sum()
df_spw=Sales_per_week

In [123]:
px.scatter_matrix(df, width=1200, height=1600)

## Preprocessing - pandas part 🐼🐼 
In this dataset, some features are removed since they are useless for the modelling.

### Remove row where target values are missing

Drop lines where target values are missing :

Here, the target variable (y) corresponds to the column Weekly_Sales. One can see above that there are some missing values in this column.
We never use imputation techniques on the target : it might create some bias in the predictions !
Then, we will just drop the lines in the dataset for which the value in Weekly_Sales is missing.

We noticed that 14 Weekly_Sales are missing in the dataset.

Since this is the target value we have no other choice than remove thes rows from the original dataset.

In [124]:
df_model = df[df['Weekly_Sales'].notna()]
print(df_model['Weekly_Sales'].isnull().sum())
df_model.describe()

0

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
count,75.000000,75,7.500000e+01,75.000000,75.000000,75.000000,75.000000,75.000000,75.0,75.0,75.0,75.0,75.0,75.0,75.0
mean,10.093333,2011-05-29 03:31:12,1.202392e+06,0.093333,60.469600,3.325920,176.073438,7.660453,2010.906667,6.533333,26.16,15.586667,0.0,0.0,0.0
min,1.000000,2010-02-05 00:00:00,2.689290e+05,0.000000,18.790000,2.548000,126.114581,5.143000,2010.0,1.0,1.0,1.0,0.0,0.0,0.0
25%,4.500000,2010-09-03 00:00:00,5.469425e+05,0.000000,45.465000,2.835000,131.033780,6.597500,2010.0,4.0,16.0,10.0,0.0,0.0,0.0
50%,10.000000,2011-05-20 00:00:00,1.074079e+06,0.000000,61.110000,3.435000,192.826069,7.470000,2011.0,6.0,25.0,16.0,0.0,0.0,0.0
75%,15.500000,2012-02-27 12:00:00,1.806773e+06,0.000000,75.180000,3.742000,214.703622,8.102500,2012.0,9.0,37.5,22.0,0.0,0.0,0.0
max,20.000000,2012-10-19 00:00:00,2.771397e+06,1.000000,91.040000,4.193000,226.968844,14.313000,2012.0,12.0,52.0,31.0,0.0,0.0,0.0
std,6.100893,NaN,6.754152e+05,0.292858,17.338982,0.494012,40.155442,1.763908,0.841063,3.120695,13.625334,8.332764,0.0,0.0,0.0

### Remove duplicate rows

In [125]:

df_model=remove_duplicates(df_model)
# rs,cs = df.shape

# df_model.drop_duplicates(inplace=True)

# if df_model.shape==(rs,cs):
#     print("\n Pas de doublon dans le jeu de données")
# else:
#     print(f'\n Nombre de doublons retirés ou coorigé dans le jeu de données  ---> {rs-df_model.shape[0]}')

 Pas de doublon dans le jeu de données

### Remove row with Not Available data

In [126]:
df_model=df_model.dropna()
df_model.reset_index(drop=True)
df_model.shape

(75, 15)

### Remove Date with date format and wrong format

Remove row with Not available Date.

In [127]:
#df=df.dropna(subset=['Date'])

In [128]:
#df_model=df_model.drop('Date', axis=1)
#df_model=df_model.drop('dt', axis=1)
df_model.reset_index(drop=True)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
0,13,2011-03-25,1807545.43,0,42.38,3.435,128.616064,7.470,2011,3,12,25,0,0,0
1,6,2010-05-28,1644470.66,0,78.89,2.759,212.412888,7.092,2010,5,21,28,0,0,0
2,15,2011-06-03,695396.19,0,69.80,4.069,134.855161,7.658,2011,6,22,3,0,0,0
3,20,2012-02-03,2203523.20,0,39.93,3.617,213.023622,6.961,2012,2,5,3,0,0,0
4,8,2011-08-19,895066.50,0,82.92,3.554,219.070197,6.425,2011,8,33,19,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,7,2012-05-25,532739.77,0,50.60,3.804,197.588605,8.090,2012,5,21,25,0,0,0
71,3,2010-06-04,396968.80,0,78.53,2.705,214.495838,7.343,2010,6,22,4,0,0,0
72,3,2012-10-19,424513.08,0,73.44,3.594,226.968844,6.034,2012,10,42,19,0,0,0
73,14,2010-06-18,2248645.59,0,72.62,2.780,182.442420,8.899,2010,6,24,18,0,0,0
74,19,2012-04-20,1255087.26,0,55.20,4.170,137.923067,8.150,2012,4,16,20,0,0,0

In [129]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
Index: 75 entries, 1 to 149
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         75 non-null     int64
 1   Date          75 non-null     datetime64[ns]
 2   Weekly_Sales  75 non-null     float64
 3   Holiday_Flag  75 non-null     int64
 4   Temperature   75 non-null     float64
 5   Fuel_Price    75 non-null     float64
 6   CPI           75 non-null     float64
 7   Unemployment  75 non-null     float64
 8   Year          75 non-null     Int64
 9   Month         75 non-null     Int64
 10  Week          75 non-null     Int64
 11  Day           75 non-null     Int64
 12  Hour          75 non-null     Int64
 13  Minute        75 non-null     Int64
 14  second        75 non-null     Int64
dtypes: Int64(7), datetime64[ns](1), float64(5), int64(2)
memory usage: 9.9 KB

In [130]:
df_model.isna().sum()

Store           0
Date            0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Year            0
Month           0
Week            0
Day             0
Hour            0
Minute          0
second          0
dtype: int64

### Analyse de la colonne Holidays Flag

La correlation est très petite entre les ventes hebdomadaire, Weekly_Sales et l'indicateur de vacances Holiday_Flag.

In [131]:
print(f"De plus, il y a seulement  {df_model['Holiday_Flag'].sum()} ligne de vacances dans le jeu de données" )
print(f"et {df_model['Holiday_Flag'].isna().sum()} valeurs manquantes sur {df_model.shape[0]} lignes.")

De plus, il y a seulement  7 ligne de vacances dans le jeu de données
et 0 valeurs manquantes sur 75 lignes.

Nous pouvvons retirer les données concernant les vacances du jeu de données. 

Ces données perturbent plus qu'elles n'aident la prédiction des ventes hebdomadaires.

In [132]:
remove_holydays = True #df_model = df_model.drop(columns=['Holiday_Flag'])

### Analyse du prix de l'essence : Fuel Price

Il n'y a pas de correlation entre les ventes hebdomadaires, Weekly_Sales, et le prix de l'essence, Fuel Price.

In [133]:
print(f"Moreover there is {df_model['Fuel_Price'].isna().sum()} Non available values over {df_model.shape[0]} rows.")

Moreover there is 0 Non available values over 75 rows.

In [134]:
df_model = df_model.drop(columns=['Fuel_Price'])
how_null_is_it(df_model)

'________________________________________________\nOverall missing values in dataset : 0\nmissing values in dataset per column \n    Store           0\nDate            0\nWeekly_Sales    0\nHoliday_Flag    0\nTemperature     0\nCPI             0\nUnemployment    0\nYear            0\nMonth           0\nWeek            0\nDay             0\nHour            0\nMinute          0\nsecond          0\ndtype: int64\n________________________________________________'

We can remove Fuel Price from this dataset data which is more a perturbation data than a descriptive data for the Weekly Sales prediction".

In [135]:
y=df_model['Weekly_Sales']
print(y)

1      1807545.43
4      1644470.66
6       695396.19
7      2203523.20
10      895066.50
          ...
139     532739.77
143     396968.80
144     424513.08
145    2248645.59
149    1255087.26
Name: Weekly_Sales, Length: 75, dtype: float64

### Outlier analysis

We track outliers to remove these rows.

In [136]:
numeric_list = ['Weekly_Sales', 'Temperature', 'CPI', 'Unemployment']

def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)]
    return outliers

for col in numeric_list:
    outliers = detect_outliers_iqr(df_model, col)
    print(f"{col} -> Outlier : {outliers.shape[0]}")

Weekly_Sales -> Outlier : 0
Temperature -> Outlier : 0
CPI -> Outlier : 0
Unemployment -> Outlier : 4

##### Unemployement outlier

In [137]:

outliers_unemp = detect_outliers_iqr(df_model, 'Unemployment')
outliers_unemp.index
#
df_model=df_model.drop(outliers_unemp.index,axis=0)
df_model.reset_index(drop=True)
display(df_model)

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
1,13,2011-03-25,1807545.43,0,42.38,128.616064,7.470,2011,3,12,25,0,0,0
4,6,2010-05-28,1644470.66,0,78.89,212.412888,7.092,2010,5,21,28,0,0,0
6,15,2011-06-03,695396.19,0,69.80,134.855161,7.658,2011,6,22,3,0,0,0
7,20,2012-02-03,2203523.20,0,39.93,213.023622,6.961,2012,2,5,3,0,0,0
10,8,2011-08-19,895066.50,0,82.92,219.070197,6.425,2011,8,33,19,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,7,2012-05-25,532739.77,0,50.60,197.588605,8.090,2012,5,21,25,0,0,0
143,3,2010-06-04,396968.80,0,78.53,214.495838,7.343,2010,6,22,4,0,0,0
144,3,2012-10-19,424513.08,0,73.44,226.968844,6.034,2012,10,42,19,0,0,0
145,14,2010-06-18,2248645.59,0,72.62,182.442420,8.899,2010,6,24,18,0,0,0
149,19,2012-04-20,1255087.26,0,55.20,137.923067,8.150,2012,4,16,20,0,0,0

## Preprocessing - scikit-learn part 🔬🔬
We will use ColumnTransformer and Pipeline from sklearn to preprocess the data before modeling.

In [138]:

from sklearn.model_selection import train_test_split
x=df_model.drop('Weekly_Sales', axis=1)
y=df_model['Weekly_Sales']
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.2,random_state= 42)
print("Train set:", x_train.shape, y_train.shape)
print("Test set:", x_test.shape, y_test.shape)

Train set: (56, 13) (56,)
Test set: (15, 13) (15,)

In [139]:
x

,Store,Date,Holiday_Flag,Temperature,CPI,Unemployment,Year,Month,Week,Day,Hour,Minute,second
1,13,2011-03-25,0,42.38,128.616064,7.470,2011,3,12,25,0,0,0
4,6,2010-05-28,0,78.89,212.412888,7.092,2010,5,21,28,0,0,0
6,15,2011-06-03,0,69.80,134.855161,7.658,2011,6,22,3,0,0,0
7,20,2012-02-03,0,39.93,213.023622,6.961,2012,2,5,3,0,0,0
10,8,2011-08-19,0,82.92,219.070197,6.425,2011,8,33,19,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,7,2012-05-25,0,50.60,197.588605,8.090,2012,5,21,25,0,0,0
143,3,2010-06-04,0,78.53,214.495838,7.343,2010,6,22,4,0,0,0
144,3,2012-10-19,0,73.44,226.968844,6.034,2012,10,42,19,0,0,0
145,14,2010-06-18,0,72.62,182.442420,8.899,2010,6,24,18,0,0,0
149,19,2012-04-20,0,55.20,137.923067,8.150,2012,4,16,20,0,0,0

In [140]:
y

1      1807545.43
4      1644470.66
6       695396.19
7      2203523.20
10      895066.50
          ...
139     532739.77
143     396968.80
144     424513.08
145    2248645.59
149    1255087.26
Name: Weekly_Sales, Length: 71, dtype: float64

Create the preprocessing pipeline for numeric columns

* list of numerical columns
* impute numeric -> median
* standardise

In [ ]:


target_col = "Weekly_Sales"



numeric_features = ["Temperature", "CPI", "Unemployment",
                    "Year", "Month", "Day"]
numerical_columns = x[numeric_features].columns.tolist() #x.select_dtypes(include=np.number).columns.tolist()
#numerical_columns =x.select_dtypes(exclude="object").columns
#, 'Year', 'Month', 'Week','Day','DayOfWeek'
numerical_columns
numeric_imputer = SimpleImputer(strategy='median')
numerical_scaler = StandardScaler()
numerical_pipeline = Pipeline(steps=[
    ('num_imputer', numeric_imputer),
    ('num_scaler', numerical_scaler),
])

['Temperature', 'CPI', 'Unemployment', 'Year', 'Month', 'Day']

Create the preprocessing pipeline for category columns

In [ ]:
#categorical_columns = x.select_dtypes(include="object").columns #x.select_dtypes(exclude=np.number).columns.tolist()
categorical_features = ["Store", "Holiday_Flag"]
categorical_columns = x[categorical_features].columns.tolist()
categorical_columns
#categorical_imputer = SimpleImputer(strategy='most_frequent')
#categorical_imputer = SimpleImputer(strategy='constant', fill_value='Unknown')

categorical_encoder = OneHotEncoder(handle_unknown="ignore")

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ('cat_encoder', categorical_encoder),
])
# Use ColumnTransformer to make a preprocessor object that describes all the treatments to be done
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features),
    ]
)


preprocessor
# ("cat", categorical_pipeline, categorical_columns),

['Store', 'Holiday_Flag']

In [146]:
print(x_test)
print()
print(x_train)

     Store       Date  Holiday_Flag  Temperature         CPI  Unemployment  \
40      18 2012-04-27             0        50.43  137.978133         8.304
1       13 2011-03-25             0        42.38  128.616064         7.470
100      3 2010-06-18             0        83.52  214.785826         7.343
10       8 2011-08-19             0        82.92  219.070197         6.425
114     11 2010-11-26             1        69.90  215.061403         7.564
35      19 2011-03-25             0        33.26  133.958742         7.771
21       5 2011-05-13             0        77.38  216.534361         6.489
59      14 2012-02-17             0        36.85  189.842483         8.424
94      14 2011-07-15             0        78.47  186.139981         8.625
23      19 2010-03-26             0        39.07  131.863129         8.350
55      13 2011-09-23             0        63.60  129.518333         6.877
20       7 2010-04-02             0        38.26  189.704822         8.963
127     16 2010-07-09             0        61.79  189.523128         6.868
11      18 2010-10-15             0        52.02  132.763355         9.331
107      8 2010-02-12             1        33.34  214.621419         6.299

     Year  Month  Week  Day  Hour  Minute  second
40   2012      4    17   27     0       0       0
1    2011      3    12   25     0       0       0
100  2010      6    24   18     0       0       0
10   2011      8    33   19     0       0       0
114  2010     11    47   26     0       0       0
35   2011      3    12   25     0       0       0
21   2011      5    19   13     0       0       0
59   2012      2     7   17     0       0       0
94   2011      7    28   15     0       0       0
23   2010      3    12   26     0       0       0
55   2011      9    38   23     0       0       0
20   2010      4    13    2     0       0       0
127  2010      7    27    9     0       0       0
11   2010     10    41   15     0       0       0
107  2010      2     6   12     0       0       0

     Store       Date  Holiday_Flag  Temperature         CPI  Unemployment  \
54      10 2012-07-06             0        86.87  130.719633         7.170
122      7 2012-09-07             1        57.84  198.095048         7.872
63       5 2012-10-19             0        69.17  224.019287         5.422
121      5 2011-07-29             0        89.42  216.046436         6.529
78       1 2011-11-18             0        62.25  218.220509         7.866
28      17 2010-04-16             0        45.22  126.562100         6.635
61      10 2012-03-02             0        57.62  130.645793         7.545
85       2 2011-01-07             0        44.69  211.064888         8.028
50      13 2012-06-01             0        61.11  130.959226         5.965
13       1 2012-03-16             0        64.74  221.211813         7.348
110     20 2010-12-31             1        28.85  204.643227         7.484
103      4 2010-12-10             0        42.40  126.793400         7.127
87       3 2012-05-11             0        75.19  225.235150         6.664
95       1 2010-05-14             0        74.78  210.337426         7.808
36       3 2011-09-23             0        80.19  219.741491         7.567
120      8 2010-09-17             0        75.32  214.878556         6.315
75      20 2010-06-25             0        75.17  204.567546         7.856
46       5 2010-07-30             0        82.46  211.927001         6.496
72      13 2010-12-10             0        36.78  126.793400         7.795
24      19 2012-05-04             0        50.76  138.033200         8.150
149     19 2012-04-20             0        55.20  137.923067         8.150
7       20 2012-02-03             0        39.93  213.023622         6.961
32       7 2012-02-10             1        18.79  196.919506         8.256
67       3 2010-02-05             0        45.71  214.424881         7.368
14      17 2010-10-01             0        60.07  126.234600         6.885
116      7 2012-04-20             0        39.30  197.722738         8.090
12       7 2011-05-13             0        36.61  192.826069         8.595
64       4 2011-12-16             0        36.44  129.898065         5.143
138      6 2011-04-22             0        74.24  217.014694         6.855
130     13 2012-03-16             0        52.50  130.826194         6.104
145     14 2010-06-18             0        72.62  182.442420         8.899
27      16 2011-05-20             0        43.95  192.831317         6.339
49      16 2012-03-30             0        48.29  197.413326         6.162
76      15 2012-03-16             0        47.42  137.584387         7.943
47      19 2010-07-02             0        66.25  132.521867         8.099
99      13 2010-07-02             0        78.82  126.139200         7.951
45       2 2012-02-24             0        54.63  220.275944         7.057
144      3 2012-10-19             0        73.44  226.968844         6.034
132      4 2011-07-22             0        82.84  129.150774         5.644
22      18 2012-10-12             0        50.97  138.911700         8.243
56       8 2010-08-27             0        74.92  214.936279         6.315
143      3 2010-06-04             0        78.53  214.495838         7.343
128     13 2011-08-12             0        75.95  129.201581         6.877
66      18 2010-08-06             0        73.67  132.614193         9.342
51       2 2010-11-12             0        59.69  211.660898         8.163
80       9 2010-11-19             0        49.96  215.437285         6.560
139      7 2012-05-25             0        50.60  197.588605         8.090
4        6 2010-05-28             0        78.89  212.412888         7.092
105     19 2010-07-30             0        72.83  132.598387         8.099
39       5 2011-11-11             0        60.71  218.569962         6.300
6       15 2011-06-03             0        69.80  134.855161         7.658
44       1 2010-02-12             1        38.51  211.242170         8.106
38       4 2011-06-24             0        81.85  129.066300         5.946
125      3 2011-11-18             0        63.91  221.643285         7.197
25      17 2012-10-12             0        44.82  131.108333         5.527
104      3 2012-06-22             0        82.70  225.306861         6.664

     Year  Month  Week  Day  Hour  Minute  second
54   2012      7    27    6     0       0       0
122  2012      9    36    7     0       0       0
63   2012     10    42   19     0       0       0
121  2011      7    30   29     0       0       0
78   2011     11    46   18     0       0       0
28   2010      4    15   16     0       0       0
61   2012      3     9    2     0       0       0
85   2011      1     1    7     0       0       0
50   2012      6    22    1     0       0       0
13   2012      3    11   16     0       0       0
110  2010     12    52   31     0       0       0
103  2010     12    49   10     0       0       0
87   2012      5    19   11     0       0       0
95   2010      5    19   14     0       0       0
36   2011      9    38   23     0       0       0
120  2010      9    37   17     0       0       0
75   2010      6    25   25     0       0       0
46   2010      7    30   30     0       0       0
72   2010     12    49   10     0       0       0
24   2012      5    18    4     0       0       0
149  2012      4    16   20     0       0       0
7    2012      2     5    3     0       0       0
32   2012      2     6   10     0       0       0
67   2010      2     5    5     0       0       0
14   2010     10    39    1     0       0       0
116  2012      4    16   20     0       0       0
12   2011      5    19   13     0       0       0
64   2011     12    50   16     0       0       0
138  2011      4    16   22     0       0       0
130  2012      3    11   16     0       0       0
145  2010      6    24   18     0       0       0
27   2011      5    20   20     0       0       0
49   2012      3    13   30     0       0       0
76   2012      3    11   16     0       0       0
47   2010      7    26    2     0       0       0
99   2010      7    26    2     0       0       0
45   2012      2     8   24     0       0       0
144  2012     10    42   19     0       0       0
132  2011      7    29   22     0       0       0
22   2012     10    41   12     0       0       0
56   2010      8    34   27     0       0       0
143  2010      6    22    4     0       0       0
128  2011      8    32   12     0       0       0
66   2010      8    31    6     0       0       0
51   2010     11    45   12     0       0       0
80   2010     11    46   19     0       0       0
139  2012      5    21   25     0       0       0
4    2010      5    21   28     0       0       0
105  2010      7    30   30     0       0       0
39   2011     11    45   11     0       0       0
6    2011      6    22    3     0       0       0
44   2010      2     6   12     0       0       0
38   2011      6    25   24     0       0       0
125  2011     11    46   18     0       0       0
25   2012     10    41   12     0       0       0
104  2012      6    25   22     0       0       0

In [147]:
# Preprocessings on train set
print("Performing preprocessings on train set...")
#print(x_train.head())
x_train = preprocessor.fit_transform(x_train)
print("...Done.")
print(
    x_train[0:5]
)  # MUST use this syntax because X_train is a numpy array and not a pandas DataFrame anymore
print()

# Preprocessings on test set
print("Performing preprocessings on test set...")
print(x_test.head())
x_test = preprocessor.transform(x_test)  # Don't fit again !! The test set is used for validating decisions
# we made based on the training set, therefore we can only apply transformations that were parametered using the training set.
# Otherwise this creates what is called a leak from the test set which will introduce a bias in all your results.
print("...Done.")
# MUST use this syntax because X_test is a numpy array and not a pandas DataFrame anymore
print()

Performing preprocessings on train set...
...Done.
[[ 1.5802326  -1.2282192  -0.04204051  1.15470054  0.11449715 -1.07095438
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          1.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.        ]
 [-0.16910349  0.46060066  0.71642506  1.15470054  0.75568116 -0.95472677
   0.          0.          0.          0.          0.          0.
   1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          1.        ]
 [ 0.51363774  1.11041291 -1.93064139  1.15470054  1.07627316  0.44000451
   0.          0.          0.          0.          1.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.        ]
 [ 1.73389458  0.91056688 -0.73459953  0.          0.11449715  1.60228058
   0.          0.          0.          0.          1.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.        ]
 [ 0.09664133  0.96506178  0.70994245  0.          1.39686517  0.3237769
   1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.        ]]

Performing preprocessings on test set...
     Store       Date  Holiday_Flag  Temperature         CPI  Unemployment  \
40      18 2012-04-27             0        50.43  137.978133         8.304
1       13 2011-03-25             0        42.38  128.616064         7.470
100      3 2010-06-18             0        83.52  214.785826         7.343
10       8 2011-08-19             0        82.92  219.070197         6.425
114     11 2010-11-26             1        69.90  215.061403         7.564

     Year  Month  Week  Day  Hour  Minute  second
40   2012      4    17   27     0       0       0
1    2011      3    12   25     0       0       0
100  2010      6    24   18     0       0       0
10   2011      8    33   19     0       0       0
114  2010     11    47   26     0       0       0
...Done.

In [148]:
print("Taille du train :", x_train.shape, " - Taille du test :", x_test.shape)

Taille du train : (56, 26)  - Taille du test : (15, 26)

## Model Training
We start training a baseline model, we'll analyze the results and we'll build improved model.
###  Baseline model (linear regression)
Once you've trained a first model, don't forget to assess its performances on the train and test sets. Are you satisfied with the results ?
Besides, it would be interesting to analyze the values of the model's coefficients to know what features are important for the prediction. To do so, the `.coef_` attribute of scikit-learn's LinearRegression class might be useful. Please refer to the following link for more information 😉 https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

In [149]:
# Model training
model = LinearRegression()
linear_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])
model.fit(x_train, y_train)

LinearRegression()

In [150]:
x_train

array([[ 1.5802326 , -1.2282192 , -0.04204051, ...,  0.        ,
         1.        ,  0.        ],
       [-0.16910349,  0.46060066,  0.71642506, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.51363774,  1.11041291, -1.93064139, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.19667226,  1.05085647, -0.01286876, ...,  0.        ,
         1.        ,  0.        ],
       [-0.95368345, -1.21847612, -1.81719568, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.32895009,  1.14268701, -0.58874076, ...,  0.        ,
         1.        ,  0.        ]], shape=(56, 26))

#### Model estimation

In [151]:
y_pred = model.predict(x_test)

# Metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Model Performance:")
print(f" train score : {model.score(x_train, y_train)}")
print(f" test score : {model.score(x_test, y_test)}")
print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.2f}")

Model Performance:
 train score : 0.98395562799872
 test score : 0.8978633031634795
MAE  : 145728.93
MSE  : 33300324809.91
RMSE : 182483.77
R²   : 0.90

In [152]:
print(x.columns)
print()
print(model.coef_)

Index(['Store', 'Date', 'Holiday_Flag', 'Temperature', 'CPI', 'Unemployment',
       'Year', 'Month', 'Week', 'Day', 'Hour', 'Minute', 'second'],
      dtype='object')

[  -70594.21700134  1036657.51314679   -73831.11547802  -123438.99646423
    12999.40697823   -41455.85850502  -580031.3563529   -319132.46454663
 -1898504.31335831  2193509.67614915 -1966353.04847463  -513478.94556512
 -1058065.34908279 -1458730.63346208 -1927798.32043814  2049099.97205666
  2089883.73778018   957380.40861702   574691.52440205 -1228636.69124036
   706887.59289122  1076140.12344273  1342591.25944973   -39453.17226788
    44864.44461506   -44864.44461507]

In [153]:
preprocessor.get_feature_names_out()

array(['num__Temperature', 'num__CPI', 'num__Unemployment', 'num__Year',
       'num__Month', 'num__Day', 'cat__Store_1', 'cat__Store_2',
       'cat__Store_3', 'cat__Store_4', 'cat__Store_5', 'cat__Store_6',
       'cat__Store_7', 'cat__Store_8', 'cat__Store_9', 'cat__Store_10',
       'cat__Store_13', 'cat__Store_14', 'cat__Store_15', 'cat__Store_16',
       'cat__Store_17', 'cat__Store_18', 'cat__Store_19', 'cat__Store_20',
       'cat__Holiday_Flag_0', 'cat__Holiday_Flag_1'], dtype=object)

In [154]:
coef_df = pd.DataFrame({
    'Feature': preprocessor.get_feature_names_out(),
    'Coefficient': model.coef_
}).sort_values(by='Coefficient', ascending=False)

print("Feature Importance (Linear Regression Coefficients):")
print(coef_df)

Feature Importance (Linear Regression Coefficients):
                Feature   Coefficient
9          cat__Store_4  2.193510e+06
16        cat__Store_13  2.089884e+06
15        cat__Store_10  2.049100e+06
22        cat__Store_19  1.342591e+06
21        cat__Store_18  1.076140e+06
1              num__CPI  1.036658e+06
17        cat__Store_14  9.573804e+05
20        cat__Store_17  7.068876e+05
18        cat__Store_15  5.746915e+05
24  cat__Holiday_Flag_0  4.486444e+04
4            num__Month  1.299941e+04
23        cat__Store_20 -3.945317e+04
5              num__Day -4.145586e+04
25  cat__Holiday_Flag_1 -4.486444e+04
0      num__Temperature -7.059422e+04
2     num__Unemployment -7.383112e+04
3             num__Year -1.234390e+05
7          cat__Store_2 -3.191325e+05
11         cat__Store_6 -5.134789e+05
6          cat__Store_1 -5.800314e+05
12         cat__Store_7 -1.058065e+06
19        cat__Store_16 -1.228637e+06
13         cat__Store_8 -1.458731e+06
8          cat__Store_3 -1.898504e+06
14         cat__Store_9 -1.927798e+06
10         cat__Store_5 -1.966353e+06

In [155]:
px.scatter(x=y_test, y=y_pred, title="Actual vs Predicted Sales", labels={"x": "Actual Sales", "y": "Predicted Sales"})

In [156]:
regressor = Ridge(alpha=0.005)
regressor.fit(x_train, y_train)
scores = cross_val_score(regressor, x_train, y_train, cv=3)
print("Cross-validation scores:", scores)
print("Average cross-validation score:", np.mean(scores))

Cross-validation scores: [0.78321608 0.77495972 0.77789469]
Average cross-validation score: 0.7786901613020559

In [157]:
regressor = Ridge()

params = {
    "alpha": [0,0.05,0.2, 0.5, 1, 1.5, 2, 3]
}

gridsearch = GridSearchCV(regressor, param_grid = params, cv = 3) # cv : the number of folds to be used for CV
gridsearch.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=Ridge(),
             param_grid={'alpha': [0, 0.05, 0.2, 0.5, 1, 1.5, 2, 3]})

In [158]:
print("Best hyperparameters : ", gridsearch.best_params_)
print("Best R2 score : ", gridsearch.best_score_)

Best hyperparameters :  {'alpha': 0.05}
Best R2 score :  0.8294309558959512

In [159]:
pd.DataFrame.from_dict(gridsearch.cv_results_).T

,0,1,2,3,4,5,6,7
mean_fit_time,0.001649,0.001053,0.001164,0.00113,0.001154,0.001402,0.001417,0.001259
std_fit_time,0.000735,0.000197,0.000091,0.000169,0.000347,0.000152,0.000253,0.000128
mean_score_time,0.000615,0.000599,0.000628,0.000761,0.000717,0.000796,0.000748,0.000742
std_score_time,0.000126,0.000067,0.00005,0.000168,0.000204,0.000048,0.000194,0.000095
param_alpha,0.0,0.05,0.2,0.5,1.0,1.5,2.0,3.0
params,{'alpha': 0},{'alpha': 0.05},{'alpha': 0.2},{'alpha': 0.5},{'alpha': 1},{'alpha': 1.5},{'alpha': 2},{'alpha': 3}
split0_test_score,-0.650536,0.873442,0.889413,0.855606,0.767061,0.686948,0.621197,0.523326
split1_test_score,0.732027,0.772374,0.742687,0.688663,0.610272,0.545171,0.491242,0.408471
split2_test_score,-0.310936,0.842477,0.839439,0.811875,0.748321,0.686327,0.631774,0.544305
mean_test_score,-0.076482,0.829431,0.823846,0.785381,0.708551,0.639482,0.581404,0.492034
std_test_score,0.588272,0.04228,0.060907,0.070682,0.069914,0.066688,0.063901,0.059705
rank_test_score,8,1,2,3,4,5,6,7

In [160]:
regressor = Lasso()

params = {
    'alpha': [0.05,0.1,0.3,0.5,0.8, 1.4, 1.5, 1.7] 
}

gridsearch = GridSearchCV(regressor, param_grid = params, cv = 3) # cv : the number of folds to be used for CV
gridsearch.fit(x_train, y_train)

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.802e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.819e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.802e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.819e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.804e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.816e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.806e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.813e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.809e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.809e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.815e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.801e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.816e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.799e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.818e+10, tolerance: 1.797e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.796e+10, tolerance: 1.760e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.611e+11, tolerance: 2.156e+09

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.383e+11, tolerance: 2.866e+09

GridSearchCV(cv=3, estimator=Lasso(),
             param_grid={'alpha': [0.05, 0.1, 0.3, 0.5, 0.8, 1.4, 1.5, 1.7]})

In [161]:
pd.DataFrame.from_dict(gridsearch.cv_results_).T.iloc[4:]

,0,1,2,3,4,5,6,7
param_alpha,0.05,0.1,0.3,0.5,0.8,1.4,1.5,1.7
params,{'alpha': 0.05},{'alpha': 0.1},{'alpha': 0.3},{'alpha': 0.5},{'alpha': 0.8},{'alpha': 1.4},{'alpha': 1.5},{'alpha': 1.7}
split0_test_score,0.742946,0.743009,0.74326,0.743513,0.74389,0.744647,0.744773,0.745023
split1_test_score,0.765184,0.765186,0.765195,0.765203,0.765217,0.765243,0.765247,0.765256
split2_test_score,0.573497,0.573626,0.57414,0.574653,0.575421,0.576951,0.577206,0.577715
mean_test_score,0.693876,0.69394,0.694198,0.694456,0.694843,0.695614,0.695742,0.695998
std_test_score,0.085603,0.085556,0.085365,0.085175,0.084891,0.084327,0.084233,0.084046
rank_test_score,8,7,6,5,4,3,2,1

In [162]:
best_regressor = gridsearch.best_estimator_
y_test_pred = best_regressor.predict(x_test)

In [163]:
r2_score(y_test, y_test_pred)

0.9279793482251605

In [164]:
best_feature_importance = pd.DataFrame(
    {
        'feature': preprocessor.get_feature_names_out(),
        'coef_linear': model.coef_,
        'coef_lasso': best_regressor.coef_
    }
)

In [165]:
features_to_keep = best_feature_importance[best_feature_importance['coef_lasso'] > 0]['feature'].tolist()
features_to_keep

['num__CPI',
 'num__Month',
 'cat__Store_2',
 'cat__Store_4',
 'cat__Store_10',
 'cat__Store_13',
 'cat__Store_14',
 'cat__Store_18',
 'cat__Store_19',
 'cat__Store_20',
 'cat__Holiday_Flag_0']

In [173]:
target_col = "Weekly_Sales"



numeric_features = [ "CPI","Month"]
numerical_columns = x[numeric_features].columns.tolist() #x.select_dtypes(include=np.number).columns.tolist()
#numerical_columns =x.select_dtypes(exclude="object").columns
#, 'Year', 'Month', 'Week','Day','DayOfWeek'
numerical_columns
numeric_imputer = SimpleImputer(strategy='median')
numerical_scaler = StandardScaler()
numerical_pipeline = Pipeline(steps=[
    ('num_imputer', numeric_imputer),
    ('num_scaler', numerical_scaler),
])
#categorical_columns = x.select_dtypes(include="object").columns #x.select_dtypes(exclude=np.number).columns.tolist()
categorical_features = ["Store"]
categorical_columns = x[categorical_features].columns.tolist()
categorical_columns
#categorical_imputer = SimpleImputer(strategy='most_frequent')
#categorical_imputer = SimpleImputer(strategy='constant', fill_value='Unknown')

categorical_encoder = OneHotEncoder(handle_unknown="ignore")

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ('cat_encoder', categorical_encoder),
])
# Use ColumnTransformer to make a preprocessor object that describes all the treatments to be done
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features),
    ]
)


preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('num_imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('num_scaler',
                                                  StandardScaler())]),
                                 ['CPI', 'Month']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('cat_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Store'])])

In [174]:
X_reduced = x[["CPI","Month","Store"]]

xr_train, xr_test, y_train, y_test = train_test_split(X_reduced, y, test_size=0.2, random_state=42)

xr_train = preprocessor.fit_transform(xr_train)
xr_test = preprocessor.transform(xr_test)

In [177]:
final_regressor = LinearRegression()

final_regressor.fit(xr_train, y_train)

print(f" Train score :  {final_regressor.score(xr_train, y_train)}")
print(f" Test score :  {final_regressor.score(xr_test, y_test)}")

 Train score :  0.9743752331123324
 Test score :  0.898839808237179

In [178]:
final_lasso = Lasso(alpha=1)

final_lasso.fit(xr_train, y_train)

print(f" Train score :  {final_lasso.score(xr_train, y_train)}")
print(f" Test score :  {final_lasso.score(xr_test, y_test)}")

 Train score :  0.9743751999403976
 Test score :  0.9059501898526054

/opt/anaconda3/envs/jedha-dsfs-ft-35/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:656: ConvergenceWarning:

Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.756e+11, tolerance: 2.866e+09

Au final, la régression linéaire simple était déjà très performante mais présentait un léger overfitting.
Après avoir testé plusieurs valeurs de régularisation Lasso, je conserve  α = 1.
il réduit l’overfitting tout en améliorant les performances en test.

## Conclusion
Dans ce projet, nous avons construit un modèle de prédiction des ventes hebdomadaires de Walmart à partir de données économiques, temporelles et commerciales. Après une phase d’exploration et de préparation des données, plusieurs modèles de régression ont été testés.

Le meilleur résultat a été obtenu avec une régression Lasso optimisée par validation croisée, atteignant un excellent niveau de performance. Les variables liées au magasin, à la temporalité et aux jours fériés apparaissent comme les plus influentes dans la prédiction des ventes.


Ce travail présente néanmoins certaines limites : le modèle reste linéaire, les variables métier disponibles sont limitées, et certaines dynamiques complexes des ventes ne sont probablement pas capturées.


Pour améliorer les performances, il serait pertinent de tester des modèles non linéaires plus avancés (Random Forest, XGBoost), d’ajouter davantage de données métier et d’approfondir l’analyse des erreurs par magasin et par période.